name: my_package_ffi
description: "A new Dart FFI package project."
version: 0.0.1

environment:
  sdk: ^3.10.4

dependencies:
  code_assets: ^0.19.7
  hooks: ^0.20.1
  logging: ^1.3.0
  native_toolchain_c: ^0.17.1

dev_dependencies:
  ffi: ^2.1.3
  ffigen: ^13.0.0
  flutter_lints: ^6.0.0
  test: ^1.25.8
