name: my_package_ffi
description: "A Flutter FFI/JNI package for BLE scanning on Android and iOS."
version: 0.0.1

environment:
  sdk: ^3.10.4
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.3
  objective_c: ^9.0.0
  jni: ^0.15.2
  hooks: ^0.20.1

dev_dependencies:
  ffigen: ^20.0.0
  jnigen: ^0.15.0
  flutter_lints: ^6.0.0
  test: ^1.25.8

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        # Les sources Objective-C sont compil√©es via CocoaPods
        pluginClass: MyPackageFfiPlugin
