name: my_package_ffi
description: "A Flutter FFI/JNI package for BLE scanning on Android and iOS."
version: 0.0.1

environment:
  sdk: ^3.10.4
  flutter: ">=3.3.0"

dependencies:
  code_assets: ^0.19.7
  ffi: ^2.1.3
  flutter:
    sdk: flutter
  hooks: ^0.20.1
  jni: ^0.15.2
  logging: ^1.3.0
  native_toolchain_c: ^0.17.1
  objective_c: ^9.0.0

dev_dependencies:
  ffigen: ^20.0.0
  flutter_lints: ^6.0.0
  jnigen: ^0.15.0
  test: ^1.25.8

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        # Les sources sont compil√©es via CocoaPods (voir ios/my_package_ffi.podspec)
        # On n'utilise pas ffiPlugin car le hook native_toolchain_c ne supporte pas bien ObjC
        pluginClass: MyPackageFfiPlugin
